name = "hey"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "hey_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "hey.wasm"
command = "npm run build:release"
